"""Inclusão de campo respondido na tabela Contato

Revision ID: 0bdbcd918f97
Revises: 8266d85329c3
Create Date: 2024-12-16 11:27:30.164087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdbcd918f97'
down_revision = '8266d85329c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
